
services:
  # -----------------------------------------------------------
  # Service 1: The Synthetic Data Generator
  # -----------------------------------------------------------
  synthea:
    build:
      context: .
      dockerfile: Dockerfile.synthea
    container_name: synthea-generator
    volumes:
      - ./raw_data:/output
    command: [
      "-p", "1000", 
      "Massachusetts", "Boston",
      "--exporter.csv.export=true",
      "--exporter.fhir.export=false",
      "--exporter.baseDirectory=/output"
    ]

  # -----------------------------------------------------------
  # Service 2: The Dagster & dbt Orchestrator
  # -----------------------------------------------------------
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagster-orchestrator
    depends_on:
      synthea:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    volumes:
      - ./raw_data:/opt/dagster/app/raw_data
      - ./.secrets:/opt/dagster/app/.secrets:ro
    env_file:
      - .env