name: SQLFluff Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-models:
    name: Lint dbt Models
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    # Set the working directory to where dbt project lives
    defaults:
      run:
        working-directory: ./transform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt and SQLFluff
        # Install the BigQuery adapter, SQLFluff, and dbt templater
        run: |
          pip install dbt-bigquery==1.11.1 sqlfluff sqlfluff-templater-dbt

      - name: Install dbt Dependencies
        run: dbt deps
      - name: Run SQLFluff Lint
        # Point dbt to the temporary key file we are about to generate
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp-key.json
        run: |
          # Securely inject the GitHub Secret into the runner's environment
          echo '${{ secrets.GCP_CREDENTIALS }}' > ./gcp-key.json
          
          # Run the linter
          sqlfluff lint models/